// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// wc_fis_by_pop
Rcpp::NumericVector wc_fis_by_pop(const Rcpp::IntegerMatrix& dat, const int pop_col, const int base);
RcppExport SEXP _shinypopgen_wc_fis_by_pop(SEXP datSEXP, SEXP pop_colSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(wc_fis_by_pop(dat, pop_col, base));
    return rcpp_result_gen;
END_RCPP
}
// boot_indiv_wc_fis_by_pop
Rcpp::NumericMatrix boot_indiv_wc_fis_by_pop(const Rcpp::IntegerMatrix& mat, const int pop_col, const int NAcode, const int B, const int base, const int debug);
RcppExport SEXP _shinypopgen_boot_indiv_wc_fis_by_pop(SEXP matSEXP, SEXP pop_colSEXP, SEXP NAcodeSEXP, SEXP BSEXP, SEXP baseSEXP, SEXP debugSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type NAcode(NAcodeSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type debug(debugSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_indiv_wc_fis_by_pop(mat, pop_col, NAcode, B, base, debug));
    return rcpp_result_gen;
END_RCPP
}
// batch_permute_wc_fis_by_pop
Rcpp::NumericMatrix batch_permute_wc_fis_by_pop(Rcpp::IntegerMatrix dat, int pop_col_1based, int base, int B);
RcppExport SEXP _shinypopgen_batch_permute_wc_fis_by_pop(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP baseSEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permute_wc_fis_by_pop(dat, pop_col_1based, base, B));
    return rcpp_result_gen;
END_RCPP
}
// fis_wc_cpp
Rcpp::List fis_wc_cpp(Rcpp::IntegerMatrix ndat, int base);
RcppExport SEXP _shinypopgen_fis_wc_cpp(SEXP ndatSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type ndat(ndatSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(fis_wc_cpp(ndat, base));
    return rcpp_result_gen;
END_RCPP
}
// wc_fis_by_pop_wc84
Rcpp::NumericVector wc_fis_by_pop_wc84(const Rcpp::IntegerMatrix& dat, int pop_col, int base);
RcppExport SEXP _shinypopgen_wc_fis_by_pop_wc84(SEXP datSEXP, SEXP pop_colSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(wc_fis_by_pop_wc84(dat, pop_col, base));
    return rcpp_result_gen;
END_RCPP
}
// batch_permute_wc_fis
NumericMatrix batch_permute_wc_fis(IntegerMatrix dat, int pop_col_1based, int base, int B, int seed);
RcppExport SEXP _shinypopgen_batch_permute_wc_fis(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permute_wc_fis(dat, pop_col_1based, base, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// calculate_observed_fis
Rcpp::NumericVector calculate_observed_fis(const Rcpp::IntegerMatrix& mat, const int pop_col, const int NAcode, const int base);
RcppExport SEXP _shinypopgen_calculate_observed_fis(SEXP matSEXP, SEXP pop_colSEXP, SEXP NAcodeSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type NAcode(NAcodeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(calculate_observed_fis(mat, pop_col, NAcode, base));
    return rcpp_result_gen;
END_RCPP
}
// boot_indiv_wc_fis
Rcpp::NumericMatrix boot_indiv_wc_fis(const Rcpp::IntegerMatrix& mat, const int pop_col, const int NAcode, const int B, const int base, const int debug, const int seed);
RcppExport SEXP _shinypopgen_boot_indiv_wc_fis(SEXP matSEXP, SEXP pop_colSEXP, SEXP NAcodeSEXP, SEXP BSEXP, SEXP baseSEXP, SEXP debugSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type NAcode(NAcodeSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type debug(debugSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_indiv_wc_fis(mat, pop_col, NAcode, B, base, debug, seed));
    return rcpp_result_gen;
END_RCPP
}
// boot_popblock_wc_fis
Rcpp::NumericMatrix boot_popblock_wc_fis(const Rcpp::IntegerMatrix& mat, const int pop_col, const int NAcode, const int B, const int base, const int seed);
RcppExport SEXP _shinypopgen_boot_popblock_wc_fis(SEXP matSEXP, SEXP pop_colSEXP, SEXP NAcodeSEXP, SEXP BSEXP, SEXP baseSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type NAcode(NAcodeSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_popblock_wc_fis(mat, pop_col, NAcode, B, base, seed));
    return rcpp_result_gen;
END_RCPP
}
// summarize_fis_results
Rcpp::List summarize_fis_results(const Rcpp::NumericMatrix& boot, const double conf);
RcppExport SEXP _shinypopgen_summarize_fis_results(SEXP bootSEXP, SEXP confSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type boot(bootSEXP);
    Rcpp::traits::input_parameter< const double >::type conf(confSEXP);
    rcpp_result_gen = Rcpp::wrap(summarize_fis_results(boot, conf));
    return rcpp_result_gen;
END_RCPP
}
// create_results_dataframe
Rcpp::DataFrame create_results_dataframe(const Rcpp::NumericVector& obs, const Rcpp::List& sum, const Rcpp::CharacterVector& locus_names);
RcppExport SEXP _shinypopgen_create_results_dataframe(SEXP obsSEXP, SEXP sumSEXP, SEXP locus_namesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type obs(obsSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type sum(sumSEXP);
    Rcpp::traits::input_parameter< const Rcpp::CharacterVector& >::type locus_names(locus_namesSEXP);
    rcpp_result_gen = Rcpp::wrap(create_results_dataframe(obs, sum, locus_names));
    return rcpp_result_gen;
END_RCPP
}
// wc84_per_allele_fstats_cpp
Rcpp::DataFrame wc84_per_allele_fstats_cpp(const Rcpp::IntegerMatrix& dat, int pop_col, int base, int missing_code);
RcppExport SEXP _shinypopgen_wc84_per_allele_fstats_cpp(SEXP datSEXP, SEXP pop_colSEXP, SEXP baseSEXP, SEXP missing_codeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    rcpp_result_gen = Rcpp::wrap(wc84_per_allele_fstats_cpp(dat, pop_col, base, missing_code));
    return rcpp_result_gen;
END_RCPP
}
// boot_wc84_fit_popblock_raw_cpp
Rcpp::List boot_wc84_fit_popblock_raw_cpp(const Rcpp::IntegerMatrix mat_int, const int pop_col, const int missing_code, const int base, const int B, const int seed, const int n_threads);
RcppExport SEXP _shinypopgen_boot_wc84_fit_popblock_raw_cpp(SEXP mat_intSEXP, SEXP pop_colSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type mat_int(mat_intSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col(pop_colSEXP);
    Rcpp::traits::input_parameter< const int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_wc84_fit_popblock_raw_cpp(mat_int, pop_col, missing_code, base, B, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// boot_wc84_stats_popblock_cpp
Rcpp::List boot_wc84_stats_popblock_cpp(const Rcpp::IntegerMatrix mat_int, const int pop_col_1based, const int missing_code, const int base, const int B, const double conf_level, const int seed, const int n_threads);
RcppExport SEXP _shinypopgen_boot_wc84_stats_popblock_cpp(SEXP mat_intSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP conf_levelSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type mat_int(mat_intSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< const int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< const int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_wc84_stats_popblock_cpp(mat_int, pop_col_1based, missing_code, base, B, conf_level, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// batch_permute_wc84_stats
Rcpp::List batch_permute_wc84_stats(const Rcpp::IntegerMatrix dat, const int pop_col_1based, const int missing_code, const int base, const int B, const int seed);
RcppExport SEXP _shinypopgen_batch_permute_wc84_stats(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< const int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permute_wc84_stats(dat, pop_col_1based, missing_code, base, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// simulate_fit_permutation_base
IntegerMatrix simulate_fit_permutation_base(const IntegerMatrix dat, const int pop_col_1based, const int missing_code, const int base);
RcppExport SEXP _shinypopgen_simulate_fit_permutation_base(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< const int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(simulate_fit_permutation_base(dat, pop_col_1based, missing_code, base));
    return rcpp_result_gen;
END_RCPP
}
// batch_permute_fit_global
Rcpp::List batch_permute_fit_global(const Rcpp::IntegerMatrix dat, const int pop_col_1based, const int missing_code, const int base, const int B, const int seed);
RcppExport SEXP _shinypopgen_batch_permute_fit_global(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< const int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< const int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type B(BSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permute_fit_global(dat, pop_col_1based, missing_code, base, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// nei_het_stats_cpp
Rcpp::List nei_het_stats_cpp(const Rcpp::IntegerMatrix& dat, int pop_col_1based, int missing_code, int base);
RcppExport SEXP _shinypopgen_nei_het_stats_cpp(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(nei_het_stats_cpp(dat, pop_col_1based, missing_code, base));
    return rcpp_result_gen;
END_RCPP
}
// observed_wc84_stats_cpp
List observed_wc84_stats_cpp(const IntegerMatrix& dat, int pop_col_1based, int missing_code, int base);
RcppExport SEXP _shinypopgen_observed_wc84_stats_cpp(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(observed_wc84_stats_cpp(dat, pop_col_1based, missing_code, base));
    return rcpp_result_gen;
END_RCPP
}
// wc84_locus_components_cpp
Rcpp::DataFrame wc84_locus_components_cpp(const Rcpp::IntegerMatrix& dat, int pop_col_1based, int missing_code, int base);
RcppExport SEXP _shinypopgen_wc84_locus_components_cpp(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    rcpp_result_gen = Rcpp::wrap(wc84_locus_components_cpp(dat, pop_col_1based, missing_code, base));
    return rcpp_result_gen;
END_RCPP
}
// locus_bootstrap_wc84_cpp
Rcpp::DataFrame locus_bootstrap_wc84_cpp(const Rcpp::NumericVector& A, const Rcpp::NumericVector& Bv, const Rcpp::NumericVector& C, const Rcpp::NumericVector& HS, const Rcpp::NumericVector& HT, int B_reps, double conf_level, double seed, int n_threads);
RcppExport SEXP _shinypopgen_locus_bootstrap_wc84_cpp(SEXP ASEXP, SEXP BvSEXP, SEXP CSEXP, SEXP HSSEXP, SEXP HTSEXP, SEXP B_repsSEXP, SEXP conf_levelSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type Bv(BvSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type C(CSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type HS(HSSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type HT(HTSEXP);
    Rcpp::traits::input_parameter< int >::type B_reps(B_repsSEXP);
    Rcpp::traits::input_parameter< double >::type conf_level(conf_levelSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(locus_bootstrap_wc84_cpp(A, Bv, C, HS, HT, B_reps, conf_level, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// batch_permute_wc84_fst_parallel
List batch_permute_wc84_fst_parallel(const IntegerMatrix& dat, int pop_col_1based, int missing_code, int base, int B, int n_threads, double seed, std::string pval_method, std::string perm_scheme);
RcppExport SEXP _shinypopgen_batch_permute_wc84_fst_parallel(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP n_threadsSEXP, SEXP seedSEXP, SEXP pval_methodSEXP, SEXP perm_schemeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< std::string >::type pval_method(pval_methodSEXP);
    Rcpp::traits::input_parameter< std::string >::type perm_scheme(perm_schemeSEXP);
    rcpp_result_gen = Rcpp::wrap(batch_permute_wc84_fst_parallel(dat, pop_col_1based, missing_code, base, B, n_threads, seed, pval_method, perm_scheme));
    return rcpp_result_gen;
END_RCPP
}
// boot_popblock_wc84_parallel
List boot_popblock_wc84_parallel(const IntegerMatrix& mat, int pop_col_1based, int missing_code, int base, int B, int n_threads, double seed);
RcppExport SEXP _shinypopgen_boot_popblock_wc84_parallel(SEXP matSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_popblock_wc84_parallel(mat, pop_col_1based, missing_code, base, B, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// boot_indiv_hs_cpp
List boot_indiv_hs_cpp(const IntegerMatrix& dat, int pop_col_1based, int missing_code, int base, int B, double seed, int n_threads);
RcppExport SEXP _shinypopgen_boot_indiv_hs_cpp(SEXP datSEXP, SEXP pop_col_1basedSEXP, SEXP missing_codeSEXP, SEXP baseSEXP, SEXP BSEXP, SEXP seedSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type dat(datSEXP);
    Rcpp::traits::input_parameter< int >::type pop_col_1based(pop_col_1basedSEXP);
    Rcpp::traits::input_parameter< int >::type missing_code(missing_codeSEXP);
    Rcpp::traits::input_parameter< int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(boot_indiv_hs_cpp(dat, pop_col_1based, missing_code, base, B, seed, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// ld_pvalues_cpp
DataFrame ld_pvalues_cpp(const StringVector& Population, const IntegerMatrix& geno_mat, const int base, const int nbperms, const int seed);
RcppExport SEXP _shinypopgen_ld_pvalues_cpp(SEXP PopulationSEXP, SEXP geno_matSEXP, SEXP baseSEXP, SEXP nbpermsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const StringVector& >::type Population(PopulationSEXP);
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type geno_mat(geno_matSEXP);
    Rcpp::traits::input_parameter< const int >::type base(baseSEXP);
    Rcpp::traits::input_parameter< const int >::type nbperms(nbpermsSEXP);
    Rcpp::traits::input_parameter< const int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(ld_pvalues_cpp(Population, geno_mat, base, nbperms, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_shinypopgen_wc_fis_by_pop", (DL_FUNC) &_shinypopgen_wc_fis_by_pop, 3},
    {"_shinypopgen_boot_indiv_wc_fis_by_pop", (DL_FUNC) &_shinypopgen_boot_indiv_wc_fis_by_pop, 6},
    {"_shinypopgen_batch_permute_wc_fis_by_pop", (DL_FUNC) &_shinypopgen_batch_permute_wc_fis_by_pop, 4},
    {"_shinypopgen_fis_wc_cpp", (DL_FUNC) &_shinypopgen_fis_wc_cpp, 2},
    {"_shinypopgen_wc_fis_by_pop_wc84", (DL_FUNC) &_shinypopgen_wc_fis_by_pop_wc84, 3},
    {"_shinypopgen_batch_permute_wc_fis", (DL_FUNC) &_shinypopgen_batch_permute_wc_fis, 5},
    {"_shinypopgen_calculate_observed_fis", (DL_FUNC) &_shinypopgen_calculate_observed_fis, 4},
    {"_shinypopgen_boot_indiv_wc_fis", (DL_FUNC) &_shinypopgen_boot_indiv_wc_fis, 7},
    {"_shinypopgen_boot_popblock_wc_fis", (DL_FUNC) &_shinypopgen_boot_popblock_wc_fis, 6},
    {"_shinypopgen_summarize_fis_results", (DL_FUNC) &_shinypopgen_summarize_fis_results, 2},
    {"_shinypopgen_create_results_dataframe", (DL_FUNC) &_shinypopgen_create_results_dataframe, 3},
    {"_shinypopgen_wc84_per_allele_fstats_cpp", (DL_FUNC) &_shinypopgen_wc84_per_allele_fstats_cpp, 4},
    {"_shinypopgen_boot_wc84_fit_popblock_raw_cpp", (DL_FUNC) &_shinypopgen_boot_wc84_fit_popblock_raw_cpp, 7},
    {"_shinypopgen_boot_wc84_stats_popblock_cpp", (DL_FUNC) &_shinypopgen_boot_wc84_stats_popblock_cpp, 8},
    {"_shinypopgen_batch_permute_wc84_stats", (DL_FUNC) &_shinypopgen_batch_permute_wc84_stats, 6},
    {"_shinypopgen_simulate_fit_permutation_base", (DL_FUNC) &_shinypopgen_simulate_fit_permutation_base, 4},
    {"_shinypopgen_batch_permute_fit_global", (DL_FUNC) &_shinypopgen_batch_permute_fit_global, 6},
    {"_shinypopgen_nei_het_stats_cpp", (DL_FUNC) &_shinypopgen_nei_het_stats_cpp, 4},
    {"_shinypopgen_observed_wc84_stats_cpp", (DL_FUNC) &_shinypopgen_observed_wc84_stats_cpp, 4},
    {"_shinypopgen_wc84_locus_components_cpp", (DL_FUNC) &_shinypopgen_wc84_locus_components_cpp, 4},
    {"_shinypopgen_locus_bootstrap_wc84_cpp", (DL_FUNC) &_shinypopgen_locus_bootstrap_wc84_cpp, 9},
    {"_shinypopgen_batch_permute_wc84_fst_parallel", (DL_FUNC) &_shinypopgen_batch_permute_wc84_fst_parallel, 9},
    {"_shinypopgen_boot_popblock_wc84_parallel", (DL_FUNC) &_shinypopgen_boot_popblock_wc84_parallel, 7},
    {"_shinypopgen_boot_indiv_hs_cpp", (DL_FUNC) &_shinypopgen_boot_indiv_hs_cpp, 7},
    {"_shinypopgen_ld_pvalues_cpp", (DL_FUNC) &_shinypopgen_ld_pvalues_cpp, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_shinypopgen(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
