# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wc_fis_by_pop <- function(dat, pop_col = 0L, base = 1000L) {
    .Call(`_shinypopgen_wc_fis_by_pop`, dat, pop_col, base)
}

boot_indiv_wc_fis_by_pop <- function(mat, pop_col = 0L, NAcode = 0L, B = 1000L, base = 1000L, debug = 0L) {
    .Call(`_shinypopgen_boot_indiv_wc_fis_by_pop`, mat, pop_col, NAcode, B, base, debug)
}

batch_permute_wc_fis_by_pop <- function(dat, pop_col_1based, base, B) {
    .Call(`_shinypopgen_batch_permute_wc_fis_by_pop`, dat, pop_col_1based, base, B)
}

fis_wc_cpp <- function(ndat, base = 1000L) {
    .Call(`_shinypopgen_fis_wc_cpp`, ndat, base)
}

wc_fis_by_pop_wc84 <- function(dat, pop_col = 0L, base = 1000L) {
    .Call(`_shinypopgen_wc_fis_by_pop_wc84`, dat, pop_col, base)
}

batch_permute_wc_fis <- function(dat, pop_col_1based, base, B, seed = 1L) {
    .Call(`_shinypopgen_batch_permute_wc_fis`, dat, pop_col_1based, base, B, seed)
}

calculate_observed_fis <- function(mat, pop_col = 0L, NAcode = 0L, base = 1000L) {
    .Call(`_shinypopgen_calculate_observed_fis`, mat, pop_col, NAcode, base)
}

boot_indiv_wc_fis <- function(mat, pop_col = 0L, NAcode = 0L, B = 1000L, base = 1000L, debug = 0L, seed = 1L) {
    .Call(`_shinypopgen_boot_indiv_wc_fis`, mat, pop_col, NAcode, B, base, debug, seed)
}

boot_popblock_wc_fis <- function(mat, pop_col = 0L, NAcode = 0L, B = 1000L, base = 1000L, seed = 1L) {
    .Call(`_shinypopgen_boot_popblock_wc_fis`, mat, pop_col, NAcode, B, base, seed)
}

summarize_fis_results <- function(boot, conf = 0.95) {
    .Call(`_shinypopgen_summarize_fis_results`, boot, conf)
}

create_results_dataframe <- function(obs, sum, locus_names) {
    .Call(`_shinypopgen_create_results_dataframe`, obs, sum, locus_names)
}

wc84_per_allele_fstats_cpp <- function(dat, pop_col = 0L, base = 1000L, missing_code = 0L) {
    .Call(`_shinypopgen_wc84_per_allele_fstats_cpp`, dat, pop_col, base, missing_code)
}

boot_wc84_fit_popblock_raw_cpp <- function(mat_int, pop_col, missing_code, base, B, seed = 1L, n_threads = 0L) {
    .Call(`_shinypopgen_boot_wc84_fit_popblock_raw_cpp`, mat_int, pop_col, missing_code, base, B, seed, n_threads)
}

boot_wc84_stats_popblock_cpp <- function(mat_int, pop_col_1based, missing_code, base, B, conf_level = 0.95, seed = 1L, n_threads = 0L) {
    .Call(`_shinypopgen_boot_wc84_stats_popblock_cpp`, mat_int, pop_col_1based, missing_code, base, B, conf_level, seed, n_threads)
}

batch_permute_wc84_stats <- function(dat, pop_col_1based, missing_code, base, B, seed = 1L) {
    .Call(`_shinypopgen_batch_permute_wc84_stats`, dat, pop_col_1based, missing_code, base, B, seed)
}

simulate_fit_permutation_base <- function(dat, pop_col_1based, missing_code, base) {
    .Call(`_shinypopgen_simulate_fit_permutation_base`, dat, pop_col_1based, missing_code, base)
}

batch_permute_fit_global <- function(dat, pop_col_1based, missing_code, base, B, seed = 1L) {
    .Call(`_shinypopgen_batch_permute_fit_global`, dat, pop_col_1based, missing_code, base, B, seed)
}

nei_het_stats_cpp <- function(dat, pop_col_1based = 1L, missing_code = 0L, base = 1000L) {
    .Call(`_shinypopgen_nei_het_stats_cpp`, dat, pop_col_1based, missing_code, base)
}

observed_wc84_stats_cpp <- function(dat, pop_col_1based = 1L, missing_code = 0L, base = 1000L) {
    .Call(`_shinypopgen_observed_wc84_stats_cpp`, dat, pop_col_1based, missing_code, base)
}

wc84_locus_components_cpp <- function(dat, pop_col_1based = 1L, missing_code = 0L, base = 1000L) {
    .Call(`_shinypopgen_wc84_locus_components_cpp`, dat, pop_col_1based, missing_code, base)
}

locus_bootstrap_wc84_cpp <- function(A, Bv, C, HS, HT, B_reps = 1000L, conf_level = 0.95, seed = 1.0, n_threads = 1L) {
    .Call(`_shinypopgen_locus_bootstrap_wc84_cpp`, A, Bv, C, HS, HT, B_reps, conf_level, seed, n_threads)
}

batch_permute_wc84_fst_parallel <- function(dat, pop_col_1based, missing_code, base, B, n_threads = 1L, seed = 1.0, pval_method = "two_sided_abs", perm_scheme = "within_pop_alleles") {
    .Call(`_shinypopgen_batch_permute_wc84_fst_parallel`, dat, pop_col_1based, missing_code, base, B, n_threads, seed, pval_method, perm_scheme)
}

boot_popblock_wc84_parallel <- function(mat, pop_col_1based = 1L, missing_code = 0L, base = 1000L, B = 1000L, n_threads = 1L, seed = 1.0) {
    .Call(`_shinypopgen_boot_popblock_wc84_parallel`, mat, pop_col_1based, missing_code, base, B, n_threads, seed)
}

boot_indiv_hs_cpp <- function(dat, pop_col_1based = 1L, missing_code = 0L, base = 1000L, B = 1000L, seed = 1.0, n_threads = 1L) {
    .Call(`_shinypopgen_boot_indiv_hs_cpp`, dat, pop_col_1based, missing_code, base, B, seed, n_threads)
}

ld_pvalues_cpp <- function(Population, geno_mat, base, nbperms = 10000L, seed = 1L) {
    .Call(`_shinypopgen_ld_pvalues_cpp`, Population, geno_mat, base, nbperms, seed)
}

